### ISSUE TITLE
Canonicalization algorithm should incorporate `@base`

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#11]
The current algorithm is based on the "incoming" `base` value only. However, the author _may_ use the JSON-LD `@base` term as part of its context, which would then overwrite the value of `base`. This is not accounted for in the algorithm.

**Comment by iherman** [comment]
I must admit I am torn on this one.

- On the one hand, `@base` is a bona fide JSON-LD feature, and all JSON-LD processors are supposed to implemenent it (and they do)
- On the other hand, we do not talk about those features in the publication manifest, just as we do not talk about a bunch of other features that JSON-LD (even 1.0) has. The current document is such that the manifest _can_ be processed by a dedicated processor without the full power of a JSON-LD one (expecting a full-blown JSON-LD processor for the publication manifest would probably be a big no-no for many implementations)

Cc @BigBlueHat @llemeurfr @rdeltour

**Comment by iherman** [comment]
(b.t.w., e.g., schema.org is also silent about `@base`, as far as I know)

**Comment by llemeurfr** [comment]
> expecting a full-blown JSON-LD processor for the publication manifest would probably be a big no-no for many implementations.

I totally agree. Publication manifests are made first for reading applications, which will simply parse the JSON structure and create objects out of them. 

Being able to create proper RDF triples from a manifest is the cherry on the cake, as it opens the door to proper SEO for web publications. but for that, the full power of JSON-LD is not necessary.

**Comment by llemeurfr** [comment]
Re. @base: this will not be usable in packaged publications, but it could be added when the publication is exposed on the Web (as a way to impose an origin to the web publication). 

but https://json-ld.org/spec/latest/json-ld/#base-iri is not clear about the use the publishing industry could make of this feature, and really this is a Web Publication question.

**Comment by BigBlueHat** [comment]
@llemeurfr fwiw, `@base` can be explicitly set to `null` in order to force them to be relative URLs.

@iherman whatever we spec here should remain compatible with its upstream foundation (i.e. JSON-LD). If there's additional processing required before it becomes valid JSON-LD, then it needs it's own MIME media type to signal the additional processing requirements. This is especially true now that the `rel="publication"` discovery mechanism is not used in every case: https://github.com/w3c/wpub/issues/409#issuecomment-490491657

**Comment by BigBlueHat** [comment]
> Being able to create proper RDF triples from a manifest is the cherry on the cake, as it opens the door to proper SEO for web publications. but for that, the full power of JSON-LD is not necessary.

@llemeurfr fwiw, the Chrome Lighthouse team is adding JSON-LD to their SEO Audits system, so JSON-LD parsing will be the foundation of those tests, and ultimately helping the SEO data be more valid and work as intended by the author of that metadata (a win for everyone).

**Comment by iherman** [comment]
@BigBlueHat this has come up before: 

> If there's additional processing required before it becomes valid JSON-LD

that is _not_ the case. We are strictly JSON-LD compliant everywhere (well, that is the intention, if it isn't true somewhere it is a bug).

**Comment by BigBlueHat** [comment]
@iherman good to know. 😃 I think our past conversations have been around the fact that the "authored" manifest and the "canonical" manifest will result in different data--i.e. they're not equivalent graphs nor would the be equivalent JSON (if the canonicalization result were re-expressed).

I'm not terribly keen on that, but that on its own doesn't justify a separate media type. Changing the way `@base` works...would.

**Comment by iherman** [comment]
@BigBlueHat, we should agree once and for all that (a) neither the authored nor the canonical manifests are deviating from JSON-LD and (b) there is no plan to change the way `@base` work.

You are right that the two manifests are not identical as RDF graphs. I am not overly fond of this either. However, a requirement to the author to systematically express all information in its full JSON-LD complexity (all links expressed as `LinkedResource` objects, all persons expressed as `Person` objects, etc.) would represent a too high entry barrier in my view. Hence this approach (I suspect schema.org does something similar, except that they do not formally define the canonicalization.)

(I do not know whether it would have any practical usefulness to add a 'profile' URL-s to the media type to differentiate between authored and canonical manifests; my gut feeling is that nobody would pay attention.)

**Comment by iherman** [comment]
There is a somewhat larger issue that we should probably mention in the document and may help us to resolve this issue.

The fact is that the Publication Manifest uses only a subset of JSON-LD. Although not formally defined this way, but it is some sort of a profile of JSON-LD. The goal is to define a useful subset that is meaningful for our target community and can be interpreted by a dedicated processor _without_ the need of a full JSON-LD processor. I guess this approach is similar to what Web Annotations, WoT, and possibly Verifiable Claims do. *If* the author wants to use the manifest to express more complex graphs using the full power of JSON-LD then he/she incurs the dangers that some reading systems would not understand the manifest.

There are number of features of JSON-LD that are not mentioned in the document. Language maps, reverse properties, named graphs, data indexing, explicit blank nodes: these are all JSON-LD 1.0 features that are not referred to, let alone the additional features that JSON-LD 1.1 adds. If we wanted to bring all those features "in", we would end up requiring a full-blown JSON-LD processor in the reading system (which is probably a big no-no, see also an implementer's, i.e., @llemeurfr's reaction in https://github.com/w3c/pub-manifest/issues/11#issuecomment-519920736). What I actually wanted to propose in https://github.com/w3c/pub-manifest/issues/11#issuecomment-519917346 is that _`@base` is one of the advanced JSON-LD features that we do not mention and use for publication manifests_. 

I.e., what I propose:

- We should actually make it clear in the document, in the form of a note, that we use a restricted version of JSON-LD only, i.e., that authors should restrict to the JSON-LD "forms" in this document. They can of course extend with additional JSON-LD features, but they do this on their own peril. I am sure @mattgarrish will find the right terminology for this.
- We should not even mention `@base` in the document...

(Maybe, when JSON-LD processors will be just as ubiquitous as HTML parsers we can issue a new version of the Publication Manifest that adds all these rich possibilities, but we are not there. Chrome Lighthouse is only for developers debugging their stuff and not for developing Web Applications with JSON-LD, i.e., the API is not, afaik, part or the browser run-time.)

**Comment by mattgarrish** [comment]
I'm all for adding an informative section to explain the relationship to json-ld. As it is, without the context of what we're trying to achieve by making authoring simple, we're bound to get questions about why we allow incomplete/invalid json-ld.

**Comment by iherman** [comment]
@mattgarrish,

"why we allow incomplete/invalid json-ld": we don't. All our metadata are bona-fide JSON-LD. The question we may get is "can I use, say, scoped contexts or JSON literals" (both are JSON-LD 1.1 goodies).

**Comment by BigBlueHat** [comment]
> would represent a too high entry barrier in my view.

For the few people typing these by hand, I'd agree, but for the vast majority of implementers (i.e. CMS's generating these manifests), I think they'd find the consistency of using the canonical representation (and the lack of "overhead" of needing it to be canonicalized every time...) to be a win.

> (I do not know whether it would have any practical usefulness to add a 'profile' URL-s to the media type to differentiate between authored and canonical manifests; my gut feeling is that nobody would pay attention.)

Though...as you mention here, there's no (consistent) way for knowing which is which (without thorough full-doc analysis), so I guess the canonicalization algorithm will be run regardless?

Sadly, we can't use [JSON-LD Framing](https://github.com/w3c/json-ld-framing/) for this as the Canonical Manifest actually introduces triples which aren't in the Authored one...

It's going to make the metadata collection world a bit painful...fwiw... Any metadata focused aggregator/consumer will have to a) know they're dealing with a Publication Manifest (vs. a normal JSON[-LD] document) and b) run the canonicalization algorithm *before* storing the metadata. Otherwise, they'll get lots of differing content since neither the JSON nor the contained graphs are consistent.

I do get the desire to have a "hand author-able" option, but...the costs still seem pretty high...

**Comment by BigBlueHat** [comment]
> The goal is to define a useful subset that is meaningful for our target community and can be interpreted by a dedicated processor _without_ the need of a full JSON-LD processor. I guess this approach is similar to what Web Annotations, WoT, and possibly Verifiable Claims do.

Each of these mentioned specs also provide a JSON Schema document (though typically non-normative) for validating their documents, and those document representations can be evaluated against those schemas and considered equivalent--even if extensions exist as those are ignored by the schema.

I'm not sure we can provide a single (or even several) JSON Schema's to validate both the Authored and Canonical versions (even without extensions) as the shapes can differ pretty drastically.

> _If_ the author wants to use the manifest to express more complex graphs using the full power of JSON-LD then he/she incurs the dangers that some reading systems would not understand the manifest.

Regardless of the above, we should spec that Reading Systems should ignore things they don't understand vs. failing. Otherwise, we'll prevent extensibility...

>     * We should actually make it clear in the document, in the form of a note, that we use a restricted version of JSON-LD only, i.e., that authors should restrict to the JSON-LD "forms" in this document.

We avoided this in Web Annotation and Verifiable Credentials(and ActivityStreams) by having a consistent JSON representation defined which could still be extended using JSON-LD's `@context` mechanism--without enforcing only a "subset" of JSON-LD be used.

Subsetting JSON-LD would also require a separate media type...fwiw.

**Comment by BigBlueHat** [comment]
> "why we allow incomplete/invalid json-ld": we don't. All our metadata are bona-fide JSON-LD. The question we may get is "can I use, say, scoped contexts or JSON literals" (both are JSON-LD 1.1 goodies).

The way we avoided this sort of subsetting in the other groups was by defining additional constraints on the JSON representation itself--typically via JSON Schema. Consequently, those groups end up with two layers of validity for their documents:
1. the document's JSON shape (validated via JSON Schema)
2. the document's JSON-LD expression--which still needed to be constrained by that shape to also be a valid Web Annotation, Verifiable Credential, etc.

That does limit how extensions are crafted as some of the key names (etc) are restricted by the spec,  but it doesn't restrict the addition of new terms, etc, so in total those approaches avoided crating a "subset" of JSON-LD by instead restricting the JSON shape/core terms, while still allowing full JSON-LD based extensions to be added later.

Interestingly all the referenced specs above make no mention of `@base` usage or calculation, but that may be due to all of them (afaict) having a preference for absolute URLs vs. relative ones (which is also true for Schema.org data fwiw).

Whatever we do lets avoid too many custom rules as that moves us into something beyond a simple "data description" format and into something much more complex and unique in the world of JSON documents.

**Comment by llemeurfr** [comment]
> The way we avoided this sort of subsetting in the other groups was by defining additional constraints on the JSON representation itself--typically via JSON Schema. 

This is a very good solution, and the one applied by another group I'm in. The JSON structure has to be well defined  (-> schema) so that reading systems can easily make objects from it, AND it should be clean JSON-LD so that publications can benefit from added seo (+ we are intellectually satisfied being part of the semantic web). 

Note that this issues has gone far from its initial title. If we have to talk again about canonicalization of the manifest, it would be good to open a new issue.

**Comment by iherman** [comment]
There actually is a JSON schema in the repository: https://github.com/w3c/pub-manifest/tree/master/schema contributed a long time ago by Hadrien Gardeur. We should find somebody who is well versed in JSON Schemas to check it and update it; I would actually be happy to make it part of the spec somehow.

"Somehow": alas!, JSON schemas are still a moving target, not standardized and (last time I checked) coming up with new, non-backward compatible versions. Hence we cannot refer to them normatively.

**Comment by iherman** [comment]
> For the few people typing these by hand, I'd agree, but for the vast majority of implementers (i.e. CMS's generating these manifests), I think they'd find the consistency of using the canonical representation (and the lack of "overhead" of needing it to be canonicalized every time...) to be a win. (@BigBlueHat)

I would be happy to reconsider the approach if there is indeed a consensus that the "complete" manifest requirement, instead of a dual approach, is acceptable. I cannot judge this.

I agree with @llemeurfr that if we go down that line, this should be raised as a separate issue... Done in #31.

**Comment by iherman** [comment]
(Administrative comment...)

I believe that there is a consensus on some aspects of the discussion, embodies by the PR #30. Although that PR still uses both manifests, i.e., it may change as a result of the discussion on #31, I think that #31 and #32 also represent the two "spin-off" discussions: the usage (or not) of a separate authoring and canonical manifest, as well as the usage (or not) of JSON Schemas.

As a consequence, I'd propose to close these issue, in favor of #31 and #32
