### ISSUE TITLE
single localizable string?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#115]
I noticed for `accessibilitySummary` and `LinkedResource/description` that the expected value category is "LocalizableString" and not "Array of LocalizableStrings".

I have to believe this is a mistake, as why couldn't you provide these in more than one language?

I can't envision a case of a property with a localizable string that wouldn't take an array of them.

**Comment by iherman** [comment]
I would defer the `accessibilitySummary` to @avneeshsingh and/or @clapierre. I agree on the `description` piece.

**Comment by avneeshsingh** [comment]
It makes sense to have multiple strings in different languages. We also need to ensure that it is in sync with schema.org definition.
When we worked with schema.org people in 2016, AccessModeSufficient was the only accessibility metadata that was identified for array representation. 
So, just a caution, we are near CR, so the changes that we make should be in sync with schema.org.

**Comment by iherman** [comment]
Thanks @avneeshsingh, I was wondering about the same thing. B.t.w., `description` is also defined similarly.

However... I believe all properties can use several text values out of the box with schema.org, as long as the order is irrelevant. The [json-ld context file for schema.org](https://schema.org/docs/jsonldcontext.json) does not preclude that, and the [google structure date testing tool](https://search.google.com/structured-data/testing-tool/u/0/) does not complain either. I tried the following test:

```
<script type='application/ld+json'>
{
"@context":"http://schema.org",
"type":"CreativeWork",
"name": "somebody",
"description": ["one","two"],
"accessibilitySummary": ["this", "and that"]
}
</script>
```

and it worked without further ado. Ie, we may be o.k.

**Comment by mattgarrish** [comment]
Right, this appears to be a case of our being more limiting than schema.org.

We've just thought of the summary in terms of a single language because most publications are not multilingual, but even in epub there's nothing to prevent you from adding it multiple times to the package document for different languages:

```
<meta property="schema:accessibilitySummary" xml:lang="en">...</meta>
<meta property="schema:accessibilitySummary" xml:lang="fr">...</meta>
```

**Comment by mattgarrish** [comment]
The summary is the only field this applies to out of the accessibility metadata, just to be clear. The rest all expect predefined tokens (literals).

AccessModeSufficient is another unique case in that each individual entry is a list, but that's a different case than being able to represent strings in multiple languages.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-10-21-pwg#section1-1).

- `RESOLVED:  the accessibilitySummary and description properties accept arrays of strings`
<details><summary><i class="differentiate">View the transcript</i></summary>
single localizable string #115<br/>
Matt Garrish: <a href="https://github.com/w3c/pub-manifest/issues/115">https://github.com/w3c/pub-manifest/issues/115</a><br/>
Matt Garrish: moving on to real topics of the day … first issue re publication manifest, issue 115, localizable strings… some minor issues have come up… just want to make sure the solutions make sense to the group<br/>
… a question of two properties… removing requirement for single values, allowing multiple languages in an array<br/>
Deborah Kaplan: the solution to make it an array makes perfect sense<br/>
Matt Garrish: the use of localizable strings works with schema.org, provides for multiple languages<br/>
Ivan Herman: correct, these have several values out of the box in schema.org… we don’t have to do anything<br/>
Matt Garrish: it’s not something that in EPUB we’ve gone into doing (multiple language a11y summaries, for example)<br/>
… we’re not breaking anything or deviating<br/>
… seems like we can resolve this<br/>
Proposed resolution: the accessibilitySummary and description properties accept arrays of strings (Ivan Herman)<br/>
Deborah Kaplan: +1<br/>
Ivan Herman: +1<br/>
Geoff Jukes: +1<br/>
Matt Garrish: +1<br/>
Mateus Teixeira: +1<br/>
George Kerscher: +1<br/>
Marisa DeMeglio: +1<br/>
Avneesh Singh: +1<br/>
Dave Cramer: +.9<br/>
Ben Schroeter: +1<br/>
Ric Wright: +1<br/>
Dave Cramer: i wonder about implicitly endorsing a design choice that every given language of a work should be in the same publication<br/>
Matt Garrish: but i don’t think we should exclude this from the possibilities<br/>
David Stroup: +1<br/>
Matt Garrish: if you need it, it’s there<br/>
Dave Cramer: yep, that’s fine<br/>
Resolution #2: the accessibilitySummary and description properties accept arrays of strings<br/>
</details>
