### ISSUE TITLE
manifest processing model, what if null base URL? (related to origin issue)

### ISSUE THREAD

**Issue by danielweck** [w3c/pub-manifest#12]
Issue originally raised in the "opaque origin" conversation:
https://github.com/w3c/wpub/issues/321#issuecomment-444409200

**Comment by iherman** [comment]
All this in a new setting, where we are "only" talking about the strict vocabulary and not the processing models anymore...

Looking at the [canonicalization algorithm](https://www.w3.org/TR/json-ld11/#embedding-json-ld-in-html-documents) the only place where the base is used is in step 11, i.e., when relative URL-s are turned into absolute ones. I see two simple options:

1. remove that step altogether. I.e., how to handle relative URL-s should be left fully under the control of the processor using the manifest, and this should be specified in the corresponding extension. I.e., one could say that if the manifest is used in a packaged audiobook, then the relative URI-s are relative to the top-level of the 'file system' within LPF.

2. alternatively, if the base is null, then all relative URLs are left as they are.

In fact, the consequence of (2) is still (1), in the sense that the processor specification should still define what a relative URI means within the publication. How is that formally defined in EPUB?

---

I mildly in favor of (2), i.e., allowing an explicit base setting but falling back on the processor behavior if not used. Note that if we decide for (1) that makes #11 moot as well.

**Comment by BigBlueHat** [comment]
@iherman looks like your "canonicalization algorithm" link is going to thew wrong spec.

I'd suggest not doing anything that forks from the JSON-LD processing semantics for `@base` and be sure to build up any "base" calculations from the same foundation from [RFC3986](https://tools.ietf.org/html/rfc3986#section-5.1).

**Comment by iherman** [comment]
I am sorry, the right link is https://w3c.github.io/pub-manifest/#canonical-manifest

**Comment by iherman** [comment]
I certainly wouldn't want to fork. (1) and (2) is to be silent about the issue in the canonicalization...

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-09-pwg#section4-7).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
5. Issue #12 Manifest processing model, what if null base URL?<br/>
Garth Conboy: Is Daniel on the call to talk about (?)<br/>
… issue 12 Manifest processing model, what if null base URL?<br/>
Garth Conboy: See Issue #12<br/>
Wendy Reid: I need to read this over before I have any opinions… I think we can save this one for discussion. Maybe Ivan has more info?<br/>
Ivan Herman: Related to what I said before - at the moment we have the publication manifest, where the base comes from is up to the various profiles…<br/>
… it was all about what happens if web content has an iframe, what is the base URL?<br/>
… we haven’t solved this issue, but it’s not relevant any more for the manifest…<br/>
Garth Conboy: Was that a ‘leave to TPAC’ or ‘close now’?<br/>
Ivan Herman: Leave to TPAC…<br/>
Garth Conboy: We’ll have Laurent with us at TPAC, so that makes sense.<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-16-pwg#section7).

- `RESOLVED:  Close Issue #12, the canonicalization algorithm has been changed, origin is no longer a concern for Publication Manifest, but should be considered for specifications concerning discovery`
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: <a href="https://github.com/w3c/pub-manifest/issues/12">https://github.com/w3c/pub-manifest/issues/12</a><br/>
Wendy Reid: this is my favorite issue!<br/>
… what if there’s a null base URL?<br/>
… in light of recent changes to the specification, we have gotten rid of the canonicalization model algorithm<br/>
… so maybe this is a non-issue<br/>
Benjamin Young: we don’t know where these json files are used<br/>
… we don’t have an origin now<br/>
… if LPF would be to go to REC, we might have to figure out how the base url is calculated<br/>
… but until this JSON file is related to some HTML document that can express a base URL, we don’t need to say anything<br/>
… it’s blank/null by default<br/>
… there are other concerns, but this issue is not an issue<br/>
Proposed resolution: Close Issue #12, the canonicalization algorithm has been removed, origin is no longer a concern for Publication Manifest (Wendy Reid)<br/>
Benjamin Young: before we vote<br/>
… the canonicalization thing has not been removed but renamed<br/>
… maybe leave that bit out<br/>
… just say it’s a json data document thingy. might not be at a URL<br/>
Ralph Swick: do you want to capture bigbluehat’s thought that this will be a concern in the future when the manifest is is included in some future transfer protocol(s)<br/>
Proposed resolution: Close Issue #12, the canonicalization algorithm has been changed, origin is no longer a concern for Publication Manifest, but should be considered for specifications concerning discovery (Wendy Reid)<br/>
Benjamin Young: +1<br/>
Wendy Reid: +1<br/>
Laurent Le Meur: +1<br/>
Gregorio Pellegrino: +1<br/>
Juan Corona: +1<br/>
Dave Cramer: +1 with an error of 1<br/>
Brady Duga: +1<br/>
Toshiaki Koike: +1<br/>
Charles LaPierre: +1<br/>
Resolution #3: Close Issue #12, the canonicalization algorithm has been changed, origin is no longer a concern for Publication Manifest, but should be considered for specifications concerning discovery<br/>
</details>
