### ISSUE TITLE
Missing validation steps on URL-s

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#137]
There are two types of 'MUST'-s that are not reflected in the validation checks:

- For the reading order and resource items the spec says that the URL-s in the linked resources MUST NOT include fragment identifiers. Although this is probably doable as part of 4.2.2.2, ie, the value category check, it may be a good idea to not this in the algorithm, because it may be forgotten (I definitely forgot). This should fall under the same heading as invalid URL-s.
- The spec also says that the resource, reading order, and link URLs MUST be mutually disjoint. I believe this step is definitely missing, and should be added in 4.4.2. at the very after 10, with the proviso that Linked Resources with urls that appear in more than one of those arrays MUST be removed

**Comment by iherman** [comment]
Actually, the extra check on whether the same URL is also repeated _within_ a list of resources is also missing from the data validation.

**Comment by dauwhe** [comment]
> Actually, the extra check on whether the same URL is also repeated _within_ a list of resources is also missing from the data validation.

See #138

**Comment by mattgarrish** [comment]
What is the expectation for processing a URL with a fragment identifier?

Seems harsh to throw the whole thing out. Is it a validation error and the fragment is stripped?

**Comment by mattgarrish** [comment]
> urls that appear in more than one of those arrays MUST be removed

I assume we give precedence to the reading order? This should probably be clarified in the prose.

**Comment by dauwhe** [comment]
> What is the expectation for processing a URL with a fragment identifier?

I think we should allow fragments in the reading order. It works just fine with the world's least sophisticated audiobook player. The whole resource would be in the bounds of the publication; when loading the resource the user agent navigates to the fragment, which is well-defined. 

Does such a restriction serve the needs of content authors or content consumers? Is it impossible to implement? I don't think so.

**Comment by mattgarrish** [comment]
> when loading the resource the user agent navigates to the fragment, which is well-defined.

But this has to be spec'd out, otherwise we're just introducing ambiguity.

A user agent could just as easily interpret a fragment as meaning only the content of the one element is in the reading order.

An author might think this is what they're doing, too, and expect the user agent to magically move the user on to the next item in the reading order at the end of the referenced element.

**Comment by dauwhe** [comment]
> But this has to be spec'd out, otherwise we're just introducing ambiguity.

Wouldn't such behavior be completely defined by the host language? 

> A user agent developer could just as easily interpret a fragment as meaning only the content of the one element is in the reading order.

Do any web user agents do this? As far as I can tell, HTML would forbid such behavior, as [navigating to a fragment](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-fragid) involves scrolling to the fragment but not suppressing other elements in the DOM. I don't think there would be any issues with audio or video.

* * *

Even making little test audiobooks today based on Librivox recordings, I would really want to use fragment IDs so that the poor reader doesn't have to listen to thirteen seconds of boilerplate at the start of each audio file. That time adds up to almost ten minutes in the Librivox Moby-Dick. Yes, I know that all Librivox recordings are in the public domain!

**Comment by mattgarrish** [comment]
> Wouldn't such behavior be completely defined by the host language?

The meaning of the fragment, but not what it means within the context of a reading order that is unknown to any format.

EPUB uses fragments to identify the range of content to show in previews, just by way of example.

My point, though, is not that it's hard or we shouldn't do it, but that we shouldn't just remove the restriction and also not say anything about what the expectations are when they're encountered. There needs to be at least a minimal explanation of what happens with a fragment identifier to avoid any confusion, which may just be to note that it indicates the starting position.

**Comment by mattgarrish** [comment]
Probably all we need to say at the generic manifest level, is that fragment identifiers are allowed and their behaviour is defined by their respective specifications. What fragments you can use and/or a user agent may actually support, is defined at the profile level.

Audiobooks can then decide whether and how to support start positions and ranges in the reading order, for example.

**Comment by iherman** [comment]
@mattgarrish will you prepare a (I think joint) PR for this and #138? It would be good to have a clear proposal that can be blessed by the group on Monday, so that we can move ahead with the CR asap...

If you have timing issues, I can find some time to do it, too.

**Comment by iherman** [comment]
Oops... I just saw that #138 is included in #131...

**Comment by mattgarrish** [comment]
I believe this is resolved with the changes in #131, and we're only awaiting consensus on the resolution in #138, so closing.
