### ISSUE TITLE
resolving prefixes in the manifest

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#141]
One issue the processing algorithm has exposed is whether it is necessary to resolve any prefixes used in the manifest. For example, should:

```
"dc:subject": "..."
```

become:

```
"http://purl.org/dc/terms/subject": "..."
```

after processing?

We've been down this road with EPUB, and my personal opinion is that this is too much complexity for the basic processing we're defining. We may want to note that care needs to be taken to ensure that prefixes are declared, properties not repeated that only differ by prefix, etc., but leave this level of validation/processing to full json-ld processors. This would be in keeping with our not supporting all of json-ld.

Validating prefixes and having predefined prefixes has led to disconnects in EPUB between what authors are allowed to do and what validators/vendors will accept at any given time. I don't see that we need these problems coming into scope for basic processing of manifests.

Ensuring our context document has a thorough list of metadata prefixes used in publishing is probably more valuable than worrying about nitpicking on authoring.

But it would be good to get group agreement on this.

**Comment by dauwhe** [comment]
If I, a well-below-average web developer, wants to do something with a publication manifest in JavaScript, I would just give up if I had to worry about resolving metadata prefixes. I'm going to see that there's a `dc:subject`, and then all I care about is extracting the content so I can display it to the user.

**Comment by iherman** [comment]
> We've been down this road with EPUB, and my personal opinion is that this is too much complexity for the basic processing we're defining. We may want to note that care needs to be taken to ensure that prefixes are declared, properties not repeated that only differ by prefix, etc., but leave this level of validation/processing to full json-ld processors. This would be in keeping with our not supporting all of json-ld.

+1 to that. (also +1 to what @dauwhe just said)

> Ensuring our context document has a thorough list of metadata prefixes used in publishing is probably more valuable than worrying about nitpicking on authoring.

Schema.org's context already has a number of predefined prefixes, like `dc` or `foaf`, ie, the average Web user does not have to deal with the exact mapping of these prefixes. We could add to our own context file a number of specialized prefixes the same way (we do inherit those from schema.org). 

There is a list in the [epub packages](https://www.w3.org/publishing/epub3/epub-packages.html#sec-metadata-reserved-prefixes) document. Out of those, adding `onix` and `marc` to our context is a no brainer, I do not think the others are to be added (`a11y` is now handled by the a11y work with schema.org). @BillKasdorf, do you think you can come with a larger list that we could adopt?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-11-04-pwg#section1-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Matt Garrish: <a href="https://github.com/w3c/pub-manifest/issues/141">https://github.com/w3c/pub-manifest/issues/141</a><br/>
Matt Garrish: yeah, there’s more<br/>
… 141, one ivan raised over the weekend, whether or not we have to resolve (URL) prefixes<br/>
Dave Cramer: NO<br/>
Ivan Herman: my answer is no…<br/>
Dave Cramer: NO<br/>
Matt Garrish: right, the answer is no, but just seeing if everyone is on board with it… we had made it a requirement in EPUB that they be resolved, and we learned it was not the best approach… it’s useful and certainly if you want json-ld processing it’s something you need, but let’s not get into validating and resolving them in our processing algorithm… let’s focus on the more useful part, creating some useful prefixes that people can use, and nothing<br/>
Mateus Teixeira: else<br/>
Garth Conboy: seems like consensus… anyone else want to chime in?<br/>
… I think “no” is where we are<br/>
Ivan Herman: right. What is our next step with this? Regarding predefined prefixes… knowing schema.org already predefines a number of prefixes… like dc and foaf, biblio… all predefined in schema.org<br/>
… do we want to add predefined prefixes in our own context?<br/>
… mattg and I were looking and some predefined ones in EPUB… maybe onix and marc would be useful?<br/>
Deborah Kaplan: <a href="https://www.loc.gov/marc/">https://www.loc.gov/marc/</a><br/>
Ivan Herman: that’s the only question, and we don’t need final list for CR because it doesn’t change the technical content of the final document in any way<br/>
Bill Kasdorf: i would advocate for keeping it informal for the extent of treating onix and marc as examples… particularly because we want it to be relevant for all kinds of publications, but we don’t want to single anything out.<br/>
Ivan Herman: the question is, which are the ones that are particularly and largely in use? Just to make the life of the user easier… there are three or four that from the outside may be useful, and it doesn’t cost anything to add them to the context<br/>
Bill Kasdorf: what’s the UA supposed to do with that<br/>
Ivan Herman: for internal representation, we don’t do anything with those… the question is, e.g., is there a reason for putting data into the manifest that is onix data?<br/>
Deborah Kaplan: agreeing with what Bill_Kasdorf says… there are a lot of prefixes that will be useful in specific contexts… there are gonna be field-specific prefixes in publishing, libraries, etc… and they won’t be there to be useful for the UA… they’re there because they identify the specific information/metadata… and the UA will probably have its own ways to handle them, but i don’t think we are going to be expecting that<br/>
… makes a lot of sense to point out specific ones that will be used a lot, but it makes less sense to make an exclusive list<br/>
… i am more in the example camp than in the specificity camp<br/>
Deborah Kaplan: MeSH, btw, is <a href="https://www.nlm.nih.gov/mesh/meshhome.html">https://www.nlm.nih.gov/mesh/meshhome.html</a><br/>
Matt Garrish: there’s an argument here… if we’re expecting profiles for specific use cases, we should maybe wait until specific prefixes are needed… but the context document is easy to update… i don’t think it’s harmful… but let’s not just add things for the sake of having a list<br/>
Benjamin Young: <a href="https://w3c.github.io/pub-manifest/#extensibility-manifest-properties">https://w3c.github.io/pub-manifest/#extensibility-manifest-properties</a><br/>
Benjamin Young: agreed with mattg… this really should be part of the profile… the key practical scenario is that whatever we don’t add in the context in the profile will be added to the context of the individual publications… so we need to acknowledge that, and publishers should know. there is danger, though, that any prefix you pick and assign a URL could be changed, you kind of want to version this and put it through a publishing oversight…<br/>
… to make sure you’re not moving things… a community using them can suffer when moving those things underneath<br/>
… when we publish a new context, it really needs a new identifier<br/>
Bill Kasdorf: the reason I’m strongly in the example camp is that it shows what to do with those things… we don’t want to discourage use of prefixes just because they haven’t been defined… we should be agnostic<br/>
Ivan Herman: I have no problem with anything that was said… the only thing I am asking here that I don’t have the answer for… EPUB does have these four or five prefixes defined, some very IDPF-specific… is there an expectation in the community that those continue to be there because they were there in EPUB? maybe we can include them just to avoid problems<br/>
Deborah Kaplan: another concern with defining specific prefix vocabularies… it runs the risk of being culturally and nationally chauvinist… in the way we’re fairly bad about in standards in general… like marc being very US-specific, being anglophone, American or West-European…<br/>
Ivan Herman: +1 to deborah (maybe it should be +10000, because this is what I seem to use:-)<br/>
Wendy Reid: +1<br/>
Bill Kasdorf: +1 to Deborah<br/>
Deborah Kaplan: we are saying in the standard by putting it in the list that we think These Are Important<br/>
Matt Garrish: to the question about whether onix or marc are necessary… i’d have to research EPUB for that, but my gut feeling is “no”<br/>
… it was very EPUB-y and strange… I would say “no”… I don’t think the mechanisms they were used for would be useful for web publications<br/>
Ivan Herman: we can propose to close the issue without further action<br/>
Wendy Reid: +1<br/>
Ivan Herman: +1 Cover Mateus Teixeira: +1<br/>
Bill Kasdorf: +1<br/>
Romain Deltour: +1<br/>
Ric Wright: +1<br/>
David Stroup: +1<br/>
Deborah Kaplan: +1<br/>
</details>

**Comment by iherman** [comment]
The decision meant no further action on this; closing
