### ISSUE TITLE
Remove Arrays of Localizable Strings from the spec

### ISSUE THREAD

**Issue by llemeurfr** [w3c/pub-manifest#205]
There are 6 occurrences of "Array of Localizable Strings" in the specification. 

Name (title), name (of an entity), name and description (of a LinkedResource), accessibilitySummary all have this value category. 

Looking at the specification of "Localizable String", we find that is is expressed as one of : a string, a LocalizableString object or an Array of Localizable String objects. It means that currently the name of a publication can be an Array of Arrays, and one can create:

"name": [{"value":"A title", "language":"en"},{"value":"Un titre", "language":"fr"}, "Ein Title", ["un título", [{"value":"Un titolo", "language":"it"},{"value":"tytułowy", "language":"pl"}]]]

which makes no sense. 

Changing the specification of the different properties to "Localizable String" will constrain the variants to something more usable: 

"name": "A title" or
"name": {"value":"A title", "language":"en"} or
"name": [{"value":"A title", "language":"en"},{"value":"Un titre", "language":"fr"},{"value":"Un titolo", "language":"it"}]

Note that the WebIDL must be modified also.

**Comment by iherman** [comment]
Hm. Isn't the bug (because there is indeed a bug!) simply that, in [§4.2.4.1](https://w3c.github.io/pub-manifest/#value-localizable-string), the definition of a Localizable String should say

> * a [json] string value; or
> * a `LocalizableString`;

Ie, the (recursive) reference to an array is simply wrong, because, as you say, the spec refers to "Arrays of Localizable strings" everywhere else in the spec.

Which also means that your first example will be incorrect, and all the valid example will be correct, and the followings will be correct, too:

"name": ["A title", "another title"]   
"name": ["A title",{"value":"Un titre", "language":"fr"}]

The WebIDL (and all our tests) will actually stay valid; all our tests were relying on this structure, where the conversion turns the simple strings into full blown objects.

@mattgarrish wdyt?

**Comment by llemeurfr** [comment]
> "name": ["A title",{"value":"Un titre", "language":"fr"}]

this is a more complex structure to handle, but it is true that it is already used for [Linked Resources](https://www.w3.org/TR/pub-manifest/#value-linked-resource).

**Comment by mattgarrish** [comment]
> Hm. Isn't the bug (because there is indeed a bug!) simply that, in [§4.2.4.1](https://w3c.github.io/pub-manifest/#value-localizable-string), the definition of a Localizable String should say
> 
> > * a [json] string value; or
> > * a `LocalizableString`;

Yes, I don't know why there's a third bullet there for an array of localizable strings. We had an issue earlier with not all value categories allowing a string, but that's been updated.

The rest looks fine. We have to allow json and localizablestring values to be mixed in an array, as that allows the default language to omitted.

**Comment by iherman** [comment]
Created a PR (#210)
