### ISSUE TITLE
Small inconsistency in the accessibility report section 

### ISSUE THREAD

**Issue by llemeurfr** [w3c/pub-manifest#207]
In the specification of the [accessibility report](https://www.w3.org/TR/pub-manifest/#accessibility-report), it is stated that "It is RECOMMENDED that the report be included as a resource of the publication so that it is available, for example, when a publication is read offline."

But the exemple just below this statement puts the property in the "links" collection, not in the "resources" collection. 

And you know ... people don't read the specs, they follow examples.

**Comment by mattgarrish** [comment]
I still kind of wonder about this recommendation. It also appears for privacy policies.

I don't know how realistic it is to expect these to be embedded, especially privacy policies which are not per-publication and could lead to stale information.

Kind of late in the game, but I wonder if these are more best practice statements and should be phrased along the lines of "It is helpful if xxx is included as a resource of the publication so that it is available when a publication is read offline, but this might not be practical in all cases."

Otherwise, yes, the example isn't invalid but doesn't match the stated expectation.

**Comment by iherman** [comment]
@mattgarrish it is probably too late to change this thing. We should just change the example (because @llemeurfr is right about people:-)

**Comment by mattgarrish** [comment]
> it is probably too late to change this thing.

Isn't the alternative more painful? Laurent notes the example error in both these sections, but we don't verify that these are not specified in the links section in the algorithm. Don't we have to write in another step to warn if they are?

That's probably why I didn't gripe about this earlier. :)

**Comment by iherman** [comment]
Hm. You may be right; changing the normative part of the spec, ie, the algorithm, is a different thing. 

+1 to you: let us go with the best practice statement (which is then an editorial change)
