### ISSUE TITLE
TAG review of Web Publications

### ISSUE THREAD

**Issue by dbaron** [w3c/pub-manifest#22]
In response to the TAG review request in w3ctag/design-reviews#344 (which originally came from w3c/wpub#384), I wanted to file an issue here (since you requested the filing of a single issue in your repo) with a pointer back to the feedback so far, which is in that issue.

There's a good bit in that issue (most of which I wrote) -- and I don't want to copy it here because I also think it's not quite done -- there were a few other TAG members who wanted to take a look and will hopefully do so soon.  However, I wanted to file this in advance of being "fully done" since you suggested that it would be useful to have the feedback prior to your face-to-face meeting next week.

One high level note would be that reading the use cases document made it sound like you were going to do a bunch of things that seem like they might be scary, but reading the actual specification seemed much less scary.  I'm not sure whether it's worth going back to the use cases document and saying how the use cases are addressed -- it might depend on how frequently you intend to point people to the use cases document in the future.

**Comment by torgo** [comment]
@mattgarrish you've proposed closing this issue. Does that mean the web publications wg is happy for us to close our review? Is there additional feedback you're looking for?

**Comment by iherman** [comment]
@torgo indeed. We did have a TAG discussion on https://github.com/w3ctag/design-reviews/issues/344 which also led to changes in the document. The present issue was not really used for the discussion, and the WG has just decided (yesterday) to close it.

We thank the TAG for its contribution, it was very valuable.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-09-pwg#section4-2).

- `RESOLVED:  close #22 without further actions`
<details><summary><i class="differentiate">View the transcript</i></summary>
issue #22 TAG Review<br/>
Garth Conboy: See Issue #22<br/>
Garth Conboy: This one should be easy, since it’s lacking content entirely - issue 22. This was a placeholder for TAG review…<br/>
Proposed resolution: close #22 without further actions (Garth Conboy)<br/>
Ivan Herman: +1<br/>
Garth Conboy: +1<br/>
Deborah Kaplan: +1<br/>
Bill Kasdorf: +1<br/>
George Kerscher: +1<br/>
Franco Alvarado: +1<br/>
Wendy Reid: +1<br/>
Charles LaPierre: +1<br/>
Ivan Herman: For the record, there has been a TAG review separately - not sure why this issue was opened<br/>
… worth mentioning that we are not ignoring TAG review, just that issue was opened and not followed up…<br/>
Resolution #4: close #22 without further actions<br/>
</details>
