### ISSUE TITLE
Should we use JSON schemas as part of the spec?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#32]
(This is a spin-off of #11.)

The manifest defines some sort of a subset of JSON-LD. It may be a good idea to use JSON Schemas to define that subset more formally.

(JSON Schemas is a moving target, so the reference can only be informative, though.)

**Comment by iherman** [comment]
Relevant comments from #11:

- https://github.com/w3c/pub-manifest/issues/11#issuecomment-520584142
- https://github.com/w3c/pub-manifest/issues/11#issuecomment-520587471
- https://github.com/w3c/pub-manifest/issues/11#issuecomment-520679416

Also, there is a version of schemas in our repository: https://github.com/w3c/pub-manifest/tree/master/schema, although it has to be updated.


@llemeurfr @BigBlueHat @mattgarrish @rdeltour

**Comment by iherman** [comment]
Further reference: https://json-schema.org/

**Comment by iherman** [comment]
Personally, I would be happy to use JSON Schemas as an extra way of defining the "shape" of our manifest. It bothers me that this cannot be done normatively, though.

(Any taker in reviewing the schemas in the repo?)

**Comment by llemeurfr** [comment]
I'm still not fond of the use of "subset of JSON-LD" (from https://github.com/w3c/pub-manifest/issues/32#issue-479981697).  It's like saying that a specific XML schema (e.g. MathML) is using a subset of the XML Schema language. The manifest is written in JSON-LD, its `context` gives it a shape (like an RDF schema does), a WebIDL construct adds more details and a JSON schema will add structural constraints. 

Proposal = use a slightly different language in the non-normative intro (#30): "A digital publication is described by a set of properties wrapped in a manifest. This manifest is expressed using the JSON-LD [[json-ld]] notation and its structure is constrained by a WebIDL [[webidl]] construct and a JSON Schema [[json-schema]]."

The fact the JSON Schemas are not standardized by an official body is unfortunate but is not a show stopper IMO. This is an industry standard, pretty stable now (since draft 07), and we would use only core / stable functionalities of the language.

The relationship between the WebIDL expression (WebIDL has been created to define interfaces) and JSON Schema (specifically designed for JSON structures) is also something to discuss: 
1/ should we maintain both? I believe this is doable and WebIDL is more readable the JSON in the spec, but no real-live software will check the validity of a manifest by its WebIDL. 
2/ can we integrate the same level of details in both? No exactly: for instance dateModified is a DOMString in the WebIDL, but can be expressed as a date-time in the JSON schema.

**Comment by iherman** [comment]
> I'm still not fond of the use of "subset of JSON-LD" (from #32 (comment)). It's like saying that a specific XML schema (e.g. MathML) is using a subset of the XML Schema language. The manifest is written in JSON-LD, its context gives it a shape (like an RDF schema does), a WebIDL construct adds more details and a JSON schema will add structural constraints.

I am not sure that is a fair comparison. An XML vocabulary is a fairly straightforward syntactical expression of its underlying data model (the XML Infoset). However, if we consider the abstract RDF model as the equivalent of the XML Infoset, JSON-LD has a very large number of various syntactical constructions expressing the same RDF model. If we did not do that, an implementation would require a full JSON-LD parser, which is way too much. 

But I may have misunderstood what you said.

> This manifest is expressed using the JSON-LD [[json-ld]] notation and its structure is constrained by a WebIDL [[webidl]] construct and a JSON Schema [[json-schema]]."

As you said yourself, WebIDL as a tool for validity will not work because there are a number of niceties that it cannot express. 

I think following the approach taken in #30 and adding a reference to the JSON Schema, saying that the constraint are expressed via the shape therein, may be sufficient.

**Comment by BigBlueHat** [comment]
@llemeurfr adding to @iherman's clarifications a bit, JSON-LD doesn't define "shape" just consistent naming/vocabulary use. JSON Schema does define shape constraints.

WebIDL is the odd one out here... Since we're not defining an client-side API, it feels pretty out of place in the world of data/document focused specifications. In fact, I don't know of any other data/document focused spec that uses it (and it caused some confusion/concern in the TAG review of WPUB as well).

**Comment by iherman** [comment]
The JSON Schema has been refreshed/updated (see #34).

@mattgarrish once #34 is merged, it is probably a good idea to add a (non-normative) reference to the JSON schema spec[1] as well as to the schema itself into the spec (probably in a note).

[1] https://json-schema.org/ or https://tools.ietf.org/html/draft-handrews-json-schema-01

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-19-pwg#section3).

- `RESOLVED:  (1) only a shape of JSON-LD is required; this will be further defined through an (informative) reference to a JSON schema. This should close issue #32. (2) instead of the canonical manifest only an internal data structure is used, and the canonicalization algo. maps onto this. This closes issue #31`
<details><summary><i class="differentiate">View the transcript</i></summary>
manifest discussion issue<br/>
Wendy Reid: See Issue #31 “Is there a need for both an authored and a canonical manifests”<br/>
Wendy Reid: See Issue #32 “Should we use JSON schemas as part of the spec?”<br/>
Wendy Reid: See summary of the discussions and decisions to be taken, read here:<br/>
Do we allow the usage of full JSON-LD for the publication manifest, or only a restricted “subset” (or shape) thereof. Put it another way, do we expect reading systems that use the manifest to include a full JSON-LD processor? (This is, in fact, issue #32.)<br/>
Do we need the differentiation (and corresponding conversion method) between an “authored” manifest and a “canonical” manifest, where the former is a simplified version of the latter (e.g., allowing the author to use simple convention to express the manifest information in its full complexity)? (See the example of @llemeurfr’s example in #31 (comment) to illustrate it)<br/>
Ivan Herman: we moved a bit last week and getting to a consensus among those who discussed all this. The proposed answer to the first question is no, ie, we would use just a specific “shape” of JSON-LD. There would be an informal reference to a JSON-Schema to define that shape.<br/>
George Kerscher: A fully implemented json processor would be able to process this subset and so would a reading system so we have this covered, yes?<br/>
Ivan Herman: yes.<br/>
… the other issue is canonical manifest. The proposed consensus is the get rid of the term ‘canonical’ manifest.<br/>
… There is already a (WebIDL) definition in the document that is used by the processor. Matt is working with the conversion algorithm that says here is the manifest and here is how I use it to convert it into the data structure defined by WebIDL. I think that the discussion on the issue shows that we are in agreement<br/>
… matt’s work is not yet done and so this will not be in the first public working draft<br/>
… the question is if there is a consensus<br/>
Wendy Reid: are there any comments?<br/>
Benjamin Young: the overall direction is the right one but we do need to review the writing when it’s done because it will clarify some of the confusion<br/>
… shape is a better term in this case than subset<br/>
Proposed resolution: (1) only a shape of JSON-LD is required; this will be further defined through an (informative) reference to a JSON schema. This should close issue #32. (2) instead of the canonical manifest only an internal data structure is used, and the canonicalization algo. maps onto this. This closes issue #31 (Ivan Herman)<br/>
Ivan Herman: +1<br/>
Wendy Reid: +1<br/>
Luc Audrain: +1<br/>
Nellie McKesson: +1<br/>
Deborah Kaplan: +1<br/>
Matt Garrish: +1<br/>
Rachel Comerford: +1<br/>
Tim Cole: +1<br/>
Romain Deltour: +1<br/>
Mateus Teixeira: +1<br/>
Geoff Jukes: +1<br/>
Benjamin Young: +1<br/>
Marisa DeMeglio: +1<br/>
Laurent Le Meur: +1<br/>
Bill Kasdorf: +1<br/>
Joshua Pyle: +1<br/>
Resolution #5: (1) only a shape of JSON-LD is required; this will be further defined through an (informative) reference to a JSON schema. This should close issue #32. (2) instead of the canonical manifest only an internal data structure is used, and the canonicalization algo. maps onto this. This closes issue #31<br/>
4. M<br/>
</details>
