### ISSUE TITLE
trimming whitespace

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#40]
We don't say anything about trimming whitespace in the processing algorithm, or generally in the specification, and JSON/JSON-LD don't define rules (that I've found). The only statement I can find in our spec about trimming is in the definition for non-empty, which just defers to other specifications for the rules.

Adding a step to trim all property names and values is simple enough, but what is the expectation if two properties end up with the same name after trimming:

```
   "name": "John Doe",
   "name ": "Jane Doe"
```

Is the second discarded or is it expected that the user agent make a "name" array for its internal representation?

Or do we avoid trimming property names (only do it for values) and the second instance just ends up an unrecognized property?

**Comment by iherman** [comment]
> Or do we avoid trimming property names (only do it for values) and the second instance just ends up an unrecognized property?

I think the latter. JSON doesn't put any restrictions of the sort on keys which can be any string, and, afaik JSON-LD doesn't put such restriction either. (JSON-LD disallows empty strings as keys, and disallows the reuse of @ keywords. That is all I found.) I don't think we should introduce extra syntactic restrictions.

@BigBlueHat ?

**Comment by mattgarrish** [comment]
I'm fine with not trimming keys, but what about trimming values?

Is that optional for user agents to do? Do value comparisons fail only because of whitespace?

**Comment by iherman** [comment]
Same as above. Neither schema.org nor json say anything about trimming...

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-09-pwg#section4-1).

- `RESOLVED:  close #40 with no action`
<details><summary><i class="differentiate">View the transcript</i></summary>
issue trimming white space, #40<br/>
Garth Conboy: See Issue #40<br/>
Garth Conboy: Issue 40 - trimming whitespace. Consensus is this is (for both names and values) that we don’t want to introduce any new constraint. Trimming not required/done…<br/>
… unless there are objections, since that’s been sitting a few days, we should go ahead and close it.<br/>
Dave Cramer: For everyone’s information, EPUB does aggressively trims whitespace on metadata values (only, not for keys since they don’t exist)<br/>
Garth Conboy: There’s commentary on keys and values here - schema.org doesn’t push us in this direction. Was Dave objecting to closing?<br/>
Dave Cramer: No.<br/>
Proposed resolution: close issue 40 with no actions (Ivan Herman)<br/>
Benjamin Young: +1<br/>
Deborah Kaplan: +1<br/>
Ivan Herman: +1<br/>
Garth Conboy: +1<br/>
Charles LaPierre: +1<br/>
Bill Kasdorf: +1<br/>
Wendy Reid: +1<br/>
Brady Duga: + 1<br/>
Mateus Teixeira: +1<br/>
Romain Deltour: +1<br/>
George Kerscher: +1<br/>
Resolution #3: close #40 with no action<br/>
</details>
