### ISSUE TITLE
Need for both inDirection and readingProgression

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#48]
Per the discussion in PR #47, there are questions about these two properties and potential overlaps between them.

- `inDirection` claims to specify the text direction for placing menus, etc., while
- `readingProgression` claims to specify resource direction for placing menus, etc.

Both define `ltr` and `rtl` as there expected values, with `readingProgression` having a default of `ltr` and `inDirection` having no default. Do we need both?

**Comment by mattgarrish** [comment]
Probably the first question we should answer here is if we need to have both these properties.

Is it valuable to know the base directions of the publication text - we will have to allow for more than one for the same reasons as `inLanguage` - or is base direction only important for the values of the manifest?

For what it's worth, EPUB doesn't provide this information.

**Comment by iherman** [comment]
Just some notes:

- If the reason of having `inDirection` is to provide more information over menus and other user interface elements, we are fine with having only one value.
- Just as for `inLanguage`, this term is not used to determine (or even provide a default) to the language and direction of the individual resources. These are mostly in HTML; HTML has its means to set the values and we should not 'interfere' with those settings.
- `readingProgression` is today set to rtl or ltf, but we heard from @llemeurfr that, in future, we may have other directions, too, for the purpose of Manga and friends. Which makes perfect sense to me. But then... this information is also to be used for the placement of menu entries and user UI goodies, which means there may indeed be an overlap.

My (not fully informed) feeling right now is that we should drop `inDirection`, because `readingDirection` may suffice.
