### ISSUE TITLE
Handling of invalid values

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#60]
We state to issue warnings when certain values are determined to be invalid, but that's dodging the issue of what a user agent has to do in these cases.

We can leave it entirely up to the user agent to determine what to do with invalid values, but we might want to look at the cases more closely to avoid implementation ambiguity.

Where the invalidity isn't significant, like dates, we might state, for example, that the reading system should not include the property in its internal representation. Likewise, if there's a default, as with reading progression, that should probably be substituted for the invalid value.

**Comment by iherman** [comment]
> Where the invalidity isn't significant, like dates, we might state, for example, that the reading system should not include the property in its internal representation. Likewise, if there's a default, as with reading progression, that should probably be substituted for the invalid value.

That sounds like a good approach to me. There may be more cases where we set a default (I have not checked).

**Comment by BigBlueHat** [comment]
If we define anything beyond what `application/json` and `application/ld+json` provide (i.e. the stuff in the [Processing a Manifest](https://www.w3.org/TR/pub-manifest/#manifest-processing) section, then we'll need a media type...by way of reminder. 😉

**Comment by iherman** [comment]
How an application uses an RDF Graph is up to the application, this does not mean that the input data must be a different media type. This is what happens here.

**Comment by BigBlueHat** [comment]
> How an application uses an RDF Graph is up to the application, this does not mean that the input data must be a different media type. This is what happens here.

This doesn't have anything to do with an RDF Graph. 😃 This has everything to do with this specification (possibly) adding additional actions to take on data contained in an `application/json` file and the need to signal that those actions MUST be taken (if they are indeed "musts" in the spec). That signalling is what media types are for...by definition.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-16-pwg#section5).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: <a href="https://github.com/w3c/pub-manifest/issues/60">https://github.com/w3c/pub-manifest/issues/60</a><br/>
Romain Deltour: there’s something about if processing does not finish, the manifest is invalid<br/>
… and we don’t say what we mean by valid<br/>
Wendy Reid: issue 60 regarding the handling of invalid values<br/>
… we say to issue warnings<br/>
… we should look more closely about what UAs should do in the case of these invalid values<br/>
Dave Cramer: At the risk of sounding like a broken record, we should make it clear for user agents, and make it testable<br/>
Wendy Reid: we should be specific… if a URL is invalid is different than if a date is invalid<br/>
Benjamin Young: to go through pub process, we need tests<br/>
… which presumes testable things<br/>
… so if we’re not clear enough we might not get out of CR<br/>
Ralph Swick: we haven’t required comprehensive test suites<br/>
… it’s up to the WG<br/>
… but for vocab, we do want to show that each term is useful, and so it must be used by two implementations<br/>
Luc Audrain: this brings back the q about audiobook check<br/>
… we have to figure out what to do with invalid values<br/>
Dave Cramer: All the people I know working for reading systems deal with invalid EPUBs every day. I’m concerned about dealing with validation.<br/>
Wendy Reid: as one of the RS people, I deal with bad EPUBs every minute<br/>
… we create behaviours for certain common errors<br/>
… we can deal with RSC-011 :)<br/>
… certain errors like mimetype or missing files are critical failures, but we had to decide based on experience<br/>
… technically we should not deal with a book with the RSC-011 but we feel we need to<br/>
Benjamin Young: issue 60 isn’t about testing, it’s about things like forcing defaults or failing on processing<br/>
… we talk about internal representations<br/>
… are we now dealing with APIs and such?<br/>
Wendy Reid: we have to steer towards a data format<br/>
… and we still have a section on processing<br/>
Benjamin Young: if we’re json-LD, and we already have processing defined–it should choke on an invalid date<br/>
Wendy Reid: we could refer to JSON-LD<br/>
</details>
