### ISSUE TITLE
Why do we have C.3 Audiobook

### ISSUE THREAD

**Issue by clapierre** [w3c/pub-manifest#74]
Since we have a specific Audiobook profile I was surprised to see a manifest example for AudioBook here.  Are we going to point to the audiobook profile, or move this over to that spec?  Just seems like if we are showing this manifest example here for Audiobooks why do we have a completely separate specification for Audiobooks.

**Comment by mattgarrish** [comment]
Wouldn't the same logic apply to the second example? The manifest isn't meant to be implemented directly, so other than showing pure json at what point do we move from theoretical examples into ones that could be mistaken for an actual format?

**Comment by iherman** [comment]
@mattgarrish I am not sure I follow what you say. We do speak about embedded manifests, so I think having an example for that is o.k.

Actually, although I +1-d the original issue, I now would say leave things as they are. The point is that there _are_ examples in the audiobook spec, so it is not particularly a problem to have an audiobooks example on both sides. The manifest spec is for all kinds of publications, and showing this in its spec looks o.k. to me.

**Comment by mattgarrish** [comment]
> We do speak about embedded manifests, so I think having an example for that is o.k.

We speak about them, but we don't define a usable format in this specification for them. The example gives the impression that you could create web pages like the example and you have ... web publications??

If we're excluding audiobook examples because we don't want to intrude on where they're defined, it seems like we shouldn't define an embedding example, either, but leave it until there is an actual format that defines the requirements.

I'm fine dropping the audiobook example, but we need to be much clearer that what remains are only hypothetical examples of how a manifest might be implemented. Otherwise, we're mixing a bit of fact and fiction.

**Comment by mattgarrish** [comment]
> ... and I think we can safely leave things as they are

I'm more comfortable with this approach with #86 adding `conformsTo` to identify the profile. It'll make clear that the first two examples are just that, examples, and that the third is an example of audiobooks.

**Comment by mattgarrish** [comment]
Any issue with closing this, @clapierre ? The example now specifies that it conforms to the audiobooks profile and there's also a reference in the title. I don't think it's problematic in itself to have an audiobooks example so long as it is clearly identified.

**Comment by clapierre** [comment]
I guess that's fine.  Do you think we need to link to the audiobook spec showing that this publication manifest is the root for the more specific example of an audiobook manifest?

**Comment by mattgarrish** [comment]
Okay, I've also linked the word "audiobooks profile": https://github.com/w3c/pub-manifest/pull/90
