### ISSUE TITLE
Reliance on type for profiles

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#83]
I hate to revisit [old issues](https://github.com/w3c/wpub/issues/351), but given the mixture of properties now in the core I'm wondering how reliable type declarations are as a means of differentiating profiles?

As I understand it, the synchronized media specification uses `duration`, but `duration` is defined in Audiobook. So if I want to synchronize some other format, and also want to be honest to schema.org, I'd have to declare it as a type.

But how do we make sense of this? Does the order of type declarations matter?

More problematic, is that we don't say anything about this being the means of identifying profiles, and should there be a registry of reserved types somewhere?

**Comment by llemeurfr** [comment]
When discussing "profiles", we must be careful about what we talking about. We are facing different types of publication, blessed by the industry: these are mainly text first publications (the original "ebooks"), audio first publications (called "audiobooks") and image first publications (called "comics", "manga", "bande dessinées" etc.).  

As an enrichment, each type can benefit from synchronized media: a traditional ebook will be enriched by a sync'ed audio narration (-> Daisy talking book or EPUB with media overlays), a comic book will be enriched by text associated with each panel and bubble (accessibility again), an audiobook may be enriched by ... why not videos of signed language?  

And any publication, whatever its type and enrichment, can be packaged when needed. Package is not a profile.

Therefore I think we can have a basic set of types (Book, Audiobook, Comicbook *) plus an additional type (SyncMedia?) when sync media is used. This is consistent with how schema.org types work. 

In this case, I see no harm calling "profiles" these different sets of types (Book, Book+SyncMedia, Audiobook, Audiobook+SyncMedia ...).

But I don't see the need for a registry, as type should have a corresponding specification. 

*: Comicbook does not exist yet in schema.org and "comic" is awfully restrictive AND anglo-saxon. A more generic token should be chosen.

**Comment by iherman** [comment]
I agree with the main lines of what @llemeurfr says: we should try to restrict ourselves to types (even if that means we would have to define some extra types if it is not covered by schema.org. Order of types does not matter.

That being said, the example is wrong: `duration` is defined in the core manifest document: https://w3c.github.io/pub-manifest/#duration

**Comment by mattgarrish** [comment]
> we should try to restrict ourselves to types

That's probably fine. I'm not questioning whether we should rely on types, but wondering why the details of our reliance are not spelled out in the specification, and why it looks like we have incompatibilities. My concern is that the issue I cited was resolved but the specification doesn't look like it's been updated to reflect the implications of it.

We don't mention that `type` identifies profiles, or that each profile has to define a unique type for itself, or that types may need to be combined not only based on schema.org properties but based on the type of publication you're creating. I'd like to fix this up, but it's not completely clear to me how the pieces are supposed to fall together.

> That being said, the example is wrong: `duration` is defined in the core manifest document:

Do you mean in the context file? The definition is wrong in that it identifies Property as its source type. I can't find it declared there.

> Order of types does not matter.

Doesn't it? Whether or not duration is the best example, what happens if you need a property from a type that's been defined for a different format? You end up with multiple types and ... whose rules and requirements and interface win? I don't think we should ignore that this may happen.

> plus an additional type (SyncMedia?) when sync media is used

That would help reduce confusion, yes.

> But I don't see the need for a registry, as type should have a corresponding specification.

Yes, but it should be easy to find out which types are already assigned and to which "profile". Finding the relevant specs and doing that manually isn't terribly user friendly. It doesn't have to be more elaborate than a wiki or a note, but it would be helpful as a reference.

**Comment by mattgarrish** [comment]
I'm also not sure how we can assume a default of CreativeWork in the absence of a type declaration. We don't define that type, so it seems like the absence of a type should be a fatal error.

**Comment by iherman** [comment]
> The definition is wrong in that it identifies Property as its source type.

Ah, that is indeed wrong. Actually, this made me realized that this 'annotation' in the right column of the definition is... unclear. In some places, like here but, also, for `inLanguage`, it refers to the [schema.org's `Property`](https://schema.org/Property), which is void of any information because it simply says that, well, it is a property in RDF sense. In some other cases (like for various types of creators) it seems to designate the publication type that this property is used on (in RDF parlance, what the domain of the property is). These are very different notions. I have the impression that these should simply be removed from the spec because they do not convey a meaningful information. I am not even sure how they got there.

It of course lets open whether we should categorize, for each term (i.e., property) we define what the domain is. Which would be quite an endeavor, and I am not sure we should do that, to be honest, because it will never be complete.

---

> We don't mention that type identifies profiles, or that each profile has to define a unique type for itself, or that types may need to be combined not only based on schema.org properties but based on the type of publication you're creating. I'd like to fix this up, but it's not completely clear to me how the pieces are supposed to fit together.

Unfortunately :-) you are right...

And... Now that we discuss this, I actually do not think (any more) that we should simply say profile=type. I would think they are different, insofar as a publication of a certain profile may use (a combination of) several types. 

> [...] what happens if you need a property from a type that's been defined for a different format? You end up with multiple types and ... whose rules and requirements and interface win? I don't think we should ignore that this may happen.

Looking at the definition of [schema.org duration](https://schema.org/duration) it lists a whole range of various types as possible domains of the property; audiobook is one of those. Which just reinforces that, indeed, profile=type is not a good option. The only thing we could say is that, e.g., an audiobook's type definition must include `Audiobook`, but it may include others. And yes, if we get to other profiles, where we define rules and requirements for the interfaces, we must avoid possible conflicts. But it is difficult to talk about these things in abstract...

**Comment by mattgarrish** [comment]
> Unfortunately :-) you are right...

Ya, I hate when that happens, too... ;)

It's certainly tricky to try and rely on schema.org type declarations when they're kind of orthogonal to the problem, and, as you say, much more diverse than we might want for profile declarations. A profile might have to be associated with a whole set of subtypes.

I keep bumping into problems trying to make a sensible model out of them given what we want, at any rate. I don't have anything better to offer, though. We could look at using something like `conformsTo`, but I hate the idea of using spec URIs. Maybe we need to mint our own `profile` property?

**Comment by llemeurfr** [comment]
What if we just and simply state that PWG specifies the use of the following types: 
Book, Audiobook (and later "Comicbook"), plus SyncMedia, the latter being only used in combination with one of the main types (e.g. Book + SyncMedia)?
This is sufficient for publishers  and UAs, I see no practical need to formally specify what a "profile" is.

**Comment by mattgarrish** [comment]
> What if we just and simply state that PWG specifies the use of the following types:

But what if I create a TechArticle profile for scholarly works? As soon as I need a property that's only defined in Book I have to declare that:

```
"type" : ["TechArticle", "Book", "SyncMedia"],
```

So what do I have? What rules does this conform to? What if I jumble it up another way:

```
"type" : ["Book", "SyncMedia", "TechArticle"],
```

Is this now a Book with properties from TechArticle?

Using schema.org types is a brittle way to define profiles given both the nature of schema.org and that we can't predict what profiles may be developed down the road.

**Comment by llemeurfr** [comment]
@mattgarrish if TechArticle IS a Book (a specialization of a Book) you don't need both. 
It should be because it is a "text first" object. 
If we really want to define profiles, we can state that
` "type" : ["TechArticle", "SyncMedia"] `
defines one (a technical article enriched with sync media content).

**Comment by mattgarrish** [comment]
> if TechArticle IS a Book (a specialization of a Book) you don't need both.

But it's not a subtype of Book in schema.org. And I can extend the manifest using any properties from any type in schema.org so long as I declare the type that they came from. So the result is that I need to put in Book to use its specific properties.

That's what makes it brittle. We can't be extensible and restrictive at the same time. I have to do one thing to conform with the expectations of how properties are declared and then another to work within this profiling we're doing and the two aren't perfectly harmonious.

**Comment by mattgarrish** [comment]
Probably the simplest solution would be to use `dcterms:conformsTo`, especially since we just put an example of this into the specification. If we declare it in the context, we can simply require:

```
"conformsTo" : "https://www.w3.org/TR/audiobooks"
```

Then we don't have to worry about overlap with the schema.org types, creating registries or anything else like that.
