### ISSUE TITLE
General issue with schemas

### ISSUE THREAD

**Issue by dauwhe** [w3c/pub-manifest#87]
It would be helpful to have a readme file for the schemas. Many people involved in this work have absolutely no experience with JSON schemas. Some basic questions:

1. What version of the JSON schema spec are we targeting? From my limited searching, this seems to make a significant difference.

2. Have our schemas been tested with particular validators? What might these be? Are they easy to set up?

3. Which schema do we actually use? I'm guessing that `publication.schema.json` is the master, and imports the others.

**Comment by mattgarrish** [comment]
>     1\. What version of the JSON schema spec are we targeting? From my limited searching, this seems to make a significant difference.

Draft 07 right now, as draft 08 just came out. Any reason not to? The [list of validators](https://json-schema.org/implementations.html#validators) on the json-schema.org site mostly show draft-07 support and there are quite a number of them.

I can attest that Oxygen has fairly good support for the schemas, although it was producing some weird default documents in the previous release (seems to be better now).

>     3\. Which schema do we actually use? I'm guessing that `publication.schema.json` is the master, and imports the others.

That's the way it works, yes.

> It would be helpful to have a readme file for the schemas.

Sure, but don't look in my direction! ;)

**Comment by llemeurfr** [comment]
We're definitely targeting draft 07 for now. 

I'm using ajv in its command line form ->[ ajv-cli](https://github.com/jessedc/ajv-cli). This is a validator written in js/ts, is simply installed using npm, supports draft 07 and is said to be very fast. 

At the moment the only issue I have with the version of the schema in the master branch is the use of "format":"iri" for "id" in contributor-object.schema.json. This is a [format introduced in draft 07](https://json-schema.org/draft-07/json-schema-release-notes.html), but doesn't seem to be supported by this tool for now.  Because the spec is using "url" for identifiers, I'll propose a PR replacing "iri" with "url" and therefore suppressing this issue.

**Comment by iherman** [comment]
I will add a small readme file (unless somebody beats me into it), referring to the current list of implementations (I still have to find the right URL), the fact that we use version 7, and indeed the entry point is `publications.schemas.json`. 

("I will" means sometimes on the week end or early next week.)

**Comment by mattgarrish** [comment]
>  but doesn't seem to be supported by this tool for now

Format is seemingly going away with the 2019-09 release:

> By default, format is no longer an assertion. This has been done because the inconsistent implementation of format as an assertion has been an endless source of surprising problems for schema authors. The default behavior will now be predictable, if not ideal. There are several ways to turn on assertion functionality, as explained below. However, we recommend doing semantic validation in the application layer.

We ultimately need something more akin to epubcheck, as there are a number of limits to what the schemas can actually check.

I don't like losing internationalization support to make a tool happy, though (there's no URL format, only URI and IRI). Since format has a tenuous future, what about using a regex as an interim solution, especially since we're limiting the schemes to http(s) and not checking that right now anyway?

**Comment by iherman** [comment]
You mean replacing the url/uri format for some regex for these? That could work, and I am sure there is a regex for url somewhere...

**Comment by mattgarrish** [comment]
> That could work, and I am sure there is a regex for url somewhere...

Yes, I grabbed an IRI regex off stack overflow and am just trying to integrate it now. Will push an update to this branch soon.

**Comment by llemeurfr** [comment]
I don't have issues with a regex to replace some format rules, but @mattgarrish, I think we have no IRI in the spec. Only URLs.

**Comment by mattgarrish** [comment]
> I think we have no IRI in the spec. Only URLs.

We're using the URL standard's definition of URL, which incorporates support for both URIs and IRIs. (Unless I'm mistaken?)

**Comment by iherman** [comment]
>> I think we have no IRI in the spec. Only URLs.
>
> We're using the URL standard's definition of URL, which incorporates support for both URIs and IRIs. (Unless I'm mistaken?)

That is correct. This was discussed in an issue (whose number I do not remember) and it was @rdeltour who drew our attention on this fact.

**Comment by mattgarrish** [comment]
I've put a very basic readme into the directory to give some direction. If anyone wants to add more to it, including known supporting validators, please feel free to edit.

Are we good to close this issue now @dauwhe ?

**Comment by dauwhe** [comment]
Much obliged, sir!
